---

- import_playbook: docker_playbook.yaml
- import_playbook: aws_playbook.yaml
- import_playbook: kubectl_playbook.yaml
- import_playbook: github_runner_playbook.yaml
- import_playbook: nexus_playbook.yaml
- import_playbook: monitoring_playbook.yaml