---
- name: Install github runnner
  hosts: aws
  become: true

  tasks:
    - name: Make runner working directory
      file:
        path: /home/ubuntu/actions-runner/
        state: directory
        owner: ubuntu
        mode: '0755'
    
    - name: Download actions-runner-linux-x64-2.296.1.tar.gz
      get_url:
        url: "https://github.com/actions/runner/releases/download/v2.296.1/actions-runner-linux-x64-2.296.1.tar.gz"
        dest: /tmp/actions-runner-linux-x64-2.296.1.tar.gz
        checksum: sha256:bc943386c499508c1841bd046f78df4f22582325c5d8d9400de980cb3613ed3b

    - name: Extract actions-runner-linux-x64-2.296.1.tar.gz
      unarchive:
        src: /tmp/actions-runner-linux-x64-2.296.1.tar.gz
        dest: /home/ubuntu/actions-runner/
        remote_src: yes

    - name: Make file permissions ok
      file:
        path: /home/ubuntu/actions-runner/
        owner:  ubuntu
        recurse: yes
        mode: 0755
      become: true

    - name: Install dependencies
      shell:
        /home/ubuntu/actions-runner/bin/installdependencies.sh

    - name: Check currently registered runners for repo
      uri:
        url: "https://api.github.com/repos/ArturTshitoyan/ACA-DevOps-Final-Project/actions/runners/registration-token"
        headers:
          Authorization: "token {{ github_token }}"
          Accept: "application/vnd.github.v3+json"
        method: POST
        status_code: 201
        force_basic_auth: yes
      register: registration
      run_once: yes

    - name: Make runner configs
      shell: |
        /home/ubuntu/actions-runner/config.sh \
        --url https://github.com/ArturTshitoyan/ACA-DevOps-Final-Project \
        --token {{ registration.json.token }} \
        --name default \
        --work _work \
        --labels default \
        --runnergroup default
      become_user: ubuntu

    - name: Create runner service
      shell: |
        cd /home/ubuntu/actions-runner/
        /home/ubuntu/actions-runner/svc.sh install
      become: true

    - name: Start runner as service
      shell: |
        cd /home/ubuntu/actions-runner/
        /home/ubuntu/actions-runner/svc.sh start
      become: true
